name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mintahandrews
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: mintahandrews
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          color_snake: '#2196F3'
          color_dots: '#2d333b, #444c56, #39d353, #26a641, #006d32'

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
